# Generated by Django 5.2.5 on 2025-09-05 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pooja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pooja_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pooja_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('poojaName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.pooja')),
            ],
        ),
        migrations.CreateModel(
            name='Pooja_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('nakshatharam', models.CharField(verbose_name=50)),
                ('date', models.CharField(verbose_name=50)),
                ('quantity', models.IntegerField()),
                ('pooja_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.pooja')),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.pooja_info')),
            ],
        ),
    ]
