# Generated by Django 5.2.5 on 2025-09-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pooja_Info_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pooja_name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=5)),
                ('special_note', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='pooja_booking',
            name='pooja_name',
            field=models.CharField(default=9, verbose_name=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pooja_info',
            name='poojaName',
        ),
        migrations.RemoveField(
            model_name='pooja_booking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pooja_info',
            name='price',
        ),
        migrations.AddField(
            model_name='pooja_info',
            name='nakshatharam',
            field=models.CharField(default=4, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pooja_info',
            name='pooja_name',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pooja',
        ),
    ]
