# Generated by Django 5.2.5 on 2025-09-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_pooja_info_table_alter_pooja_booking_pooja_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooja_info_table',
            name='duration',
            field=models.CharField(max_length=15),
        ),
    ]
