# Generated by Django 5.2.5 on 2025-09-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_pooja_info_table_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pooja_Info_Table',
        ),
        migrations.AddField(
            model_name='pooja_booking',
            name='phone_number',
            field=models.CharField(default=55, max_length=10),
            preserve_default=False,
        ),
    ]
