# Generated by Django 5.2.5 on 2025-09-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_delete_pooja_info_table_pooja_booking_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nakshatharam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nakshatharam', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pooja_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pooja_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Pooja_Info',
        ),
    ]
