# Generated by Django 5.2.5 on 2025-09-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_nakshatharam_pooja_name_delete_pooja_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pooja_booking',
            old_name='date',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='pooja_booking',
            old_name='nakshatharam',
            new_name='nak',
        ),
        migrations.RenameField(
            model_name='pooja_booking',
            old_name='pooja_name',
            new_name='poojaname',
        ),
    ]
