# Generated by Django 5.2.5 on 2025-09-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_rename_date_pooja_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pooja_Booking',
            new_name='PoojaBooking',
        ),
    ]
